# Introduction #

In this exercise you'll start developing the features you identified in Exercise 2 as having the most potential. As you work through this exercise, you might take a moment to look at the data documentation again and consider whether the features we're creating make sense from a real-world perspective, and whether there are any useful combinations that stand out to you.

Run this cell to set everything up!

In [28]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor


def score_dataset(X, y, model=XGBRegressor()):
    # Label encoding for categoricals
    for colname in X.select_dtypes(["category", "object", "str"]):
        X[colname], _ = X[colname].factorize()

    score = cross_val_score(model, X, y, cv=5, scoring="neg_mean_squared_log_error",)
    score = -1 * score.mean()
    score = np.sqrt(score)
    return score

# Prepare data
df = pd.read_csv("../datasets/ames-housing-dataset/ames.csv")
X = df.copy()
y = X.pop("SalePrice")

-------------------------------------------------------------------------------

Let's start with a few mathematical combinations. We'll focus on features describing areas -- having the same units (square-feet) makes it easy to combine them in sensible ways. Since we're using XGBoost (a tree-based model), we'll focus on ratios and sums.

# 1) Create Mathematical Transforms

Create the following features:

- `LivLotRatio`: the ratio of `GrLivArea` to `LotArea`
- `Spaciousness`: the sum of `FirstFlrSF` and `SecondFlrSF` divided by `TotRmsAbvGrd`
- `TotalOutsideSF`: the sum of `WoodDeckSF`, `OpenPorchSF`, `EnclosedPorch`, `Threeseasonporch`, and `ScreenPorch`

In [29]:
X_1 = pd.DataFrame()  # dataframe to hold new features

X_1["LivLotRatio"] = X["GrLivArea"] / X["LotArea"]
X_1["Spaciousness"] = (X["FirstFlrSF"] + X["SecondFlrSF"]) / X["TotRmsAbvGrd"]
X_1["TotalOutsideSF"] = X["WoodDeckSF"] + X["OpenPorchSF"] + X["EnclosedPorch"] + X["Threeseasonporch"] + X["ScreenPorch"]

X_1.head()

   LivLotRatio  Spaciousness  TotalOutsideSF
0     0.052125    236.571429           272.0
1     0.077095    179.200000           260.0
2     0.093152    221.500000           429.0
3     0.189068    263.750000             0.0
4     0.117787    271.500000           246.0

-------------------------------------------------------------------------------

If you've discovered an interaction effect between a numeric feature and a categorical feature, you might want to model it explicitly using a one-hot encoding, like so:

```
# One-hot encode Categorical feature, adding a column prefix "Cat"
X_new = pd.get_dummies(df.Categorical, prefix="Cat")

# Multiply row-by-row
X_new = X_new.mul(df.Continuous, axis=0)

# Join the new features to the feature set
X = X.join(X_new)
```

# 2) Interaction with a Categorical

We discovered an interaction between `BldgType` and `GrLivArea` in Exercise 2. Now create their interaction features.

In [30]:
X_2 = pd.get_dummies(df.BldgType, prefix="Bldg")
X_2 = X_2.mul(df.GrLivArea, axis=0)
X_2

      Bldg_Duplex  Bldg_OneFam  Bldg_Twnhs  Bldg_TwnhsE  Bldg_TwoFmCon
0             0.0       1656.0         0.0          0.0            0.0
1             0.0        896.0         0.0          0.0            0.0
2             0.0       1329.0         0.0          0.0            0.0
3             0.0       2110.0         0.0          0.0            0.0
4             0.0       1629.0         0.0          0.0            0.0
...           ...          ...         ...          ...            ...
2925          0.0       1003.0         0.0          0.0            0.0
2926          0.0        902.0         0.0          0.0            0.0
2927          0.0        970.0         0.0          0.0            0.0
2928          0.0       1389.0         0.0          0.0            0.0
2929          0.0       2000.0         0.0          0.0            0.0

[2930 rows x 5 columns]

# 3) Count Feature

Let's try creating a feature that describes how many kinds of outdoor areas a dwelling has. Create a feature `PorchTypes` that counts how many of the following are greater than 0.0:

```
WoodDeckSF
OpenPorchSF
EnclosedPorch
Threeseasonporch
ScreenPorch
```

In [31]:
X_3 = pd.DataFrame()
features = ["WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "Threeseasonporch", "ScreenPorch"]
X_3["PorchTypes"] = X[features].gt(0.0).sum(axis=1)
X_3

      PorchTypes
0              2
1              2
2              2
3              0
4              2
...          ...
2925           1
2926           1
2927           2
2928           2
2929           2

[2930 rows x 1 columns]

# 4) Break Down a Categorical Feature

`MSSubClass` describes the type of a dwelling:

In [32]:
df.MSSubClass.unique()

<StringArray>
[      'One_Story_1946_and_Newer_All_Styles',
                  'Two_Story_1946_and_Newer',
              'One_Story_PUD_1946_and_Newer',
      'One_and_Half_Story_Finished_All_Ages',
                               'Split_Foyer',
              'Two_Story_PUD_1946_and_Newer',
                       'Split_or_Multilevel',
                  'One_Story_1945_and_Older',
                'Duplex_All_Styles_and_Ages',
 'Two_Family_conversion_All_Styles_and_Ages',
    'One_and_Half_Story_Unfinished_All_Ages',
                  'Two_Story_1945_and_Older',
               'Two_and_Half_Story_All_Ages',
    'One_Story_with_Finished_Attic_All_Ages',
          'PUD_Multilevel_Split_Level_Foyer',
           'One_and_Half_Story_PUD_All_Ages']
Length: 16, dtype: str

You can see that there is a more general categorization described (roughly) by the first word of each category. Create a feature containing only these first words by splitting `MSSubClass` at the first underscore `_`. (Hint: In the `split` method use an argument `n=1`.)

In [33]:
X_4 = pd.DataFrame()
X_4["MSClass"] = X.MSSubClass.str.split("_", n=1, expand=True)[0]
X_4

     MSClass
0        One
1        One
2        One
3        One
4        Two
...      ...
2925   Split
2926     One
2927   Split
2928     One
2929     Two

[2930 rows x 1 columns]

# 5) Use a Grouped Transform

The value of a home often depends on how it compares to typical homes in its neighborhood. Create a feature `MedNhbdArea` that describes the *median* of `GrLivArea` grouped on `Neighborhood`.

In [34]:
X_5 = pd.DataFrame()
X_5["MedNhbdArea"] = X.groupby("Neighborhood")["GrLivArea"].transform("median")
X_5

      MedNhbdArea
0          1200.0
1          1200.0
2          1200.0
3          1200.0
4          1560.0
...           ...
2925       1282.0
2926       1282.0
2927       1282.0
2928       1282.0
2929       1282.0

[2930 rows x 1 columns]

In [35]:
X_new = X.join([X_1, X_2, X_3, X_4, X_5])
print(score_dataset(X, y))
print(score_dataset(X_new, y))

0.14261750108636856
0.139566062426937